# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
