# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='batch_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
